version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
